runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- remote_api: on
- appstats: on

libraries:
- name: django
  version: "1.2"
- name: PIL
  version: "1.1.7"

handlers:
- url: /static
  static_dir: static
  expiration: '30d'
  secure: always

- url: /(canvas.html|crossdomain.xml|favicon.ico|favicon.png|rpc_relay.html|robots.txt)
  static_files: static/\1
  upload: static/(canvas.html|crossdomain.xml|favicon.ico|favicon.png|rpc_relay.html|robots.txt)
  expiration: '30d'
  secure: always

- url: /.*
  script: request.application
  secure: always
