runtime: python312

app_engine_apis: true

builtins:
- deferred: on
- remote_api: on
- appstats: on

automatic_scaling:
  max_instances: 2

handlers:
- url: /static
  static_dir: static
  expiration: '30d'
  secure: always

- url: /(canvas.html|crossdomain.xml|favicon.ico|favicon.png|rpc_relay.html|robots.txt)
  static_files: static/\1
  upload: static/(canvas.html|crossdomain.xml|favicon.ico|favicon.png|rpc_relay.html|robots.txt)
  expiration: '30d'
  secure: always

- url: /.*
  script: auto
  secure: always
